name: ecomorse
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

 #? ================= packages =================
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  iconsax: ^0.0.8
  shared_preferences: ^2.3.1

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.jpeg"
  










#=============================== ميخصناش ===================


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
#================================== ده يخصنا عادي =============================
  assets:
    - assets/image/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Schyler
      fonts:
        - asset: assets/font/Pacifico-Regular.ttf
    - family: font2
      fonts:
        - asset: assets\font\Kemio-SemiExpanded.otf
    - family: font3
      fonts:
        - asset: assets\font\Mont-HeavyDEMO.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  